@RabbitMQTest.API_HostAddress = http://localhost:5081

POST {{RabbitMQTest.API_HostAddress}}/rabbitmq
Content-Type: application/json
Accept: application/json

{
    "studentName": "Bruno Protti",
    "age": 26,
    "courseTitle": "RabbitMQ testing"
}

###
